### ISSUE TITLE
List of search to choose from 

### ISSUE THREAD

**Issue by Gourav1910** [onuraycicek/obsidian-movie#1]
As in your demo video/gif you have put a movie name and it's note appeared. But is it necessary to put the exact name of the movie? Can't we just start typing and choose from the list so that we can pick the exact movie in case movie has multiple sequels or remakes.

**Comment by onuraycicek** [comment]
I used OMDB's api to pull information about the movie or series. For the trailer, it takes the link of the first result by searching on Youtube. Currently not in stable version. It is likely to receive an update soon. If you want to contribute, feel free.
